name: VPS Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Webhook Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Webhook Git Pull
        run: |
          curl -f -s "https://iconstash.io/deploy.php?token=${{ secrets.DEPLOY_TOKEN }}"
